This is a testharness.js-based test.
[FAIL] Second request should come from the cache and not hit the server.
  promise_test: Unhandled rejection with value: object "NetworkError: Error retrieving a token."
Harness: the test ran to completion.

