[gen-gatt-op-disconnect-called-during-success.https.html]
  [disconnect() called during a writeValueWithResponse call that succeeds. Reject with NetworkError.]
    expected: FAIL
