This is a testharness.js-based test.
[FAIL] no reserved.once in reporting
  promise_test: Unhandled rejection with value: object "DataError: Failed to execute 'runAdAuction' on 'Navigator': aggregationCoordinatorOrigin 'https://web-platform.test:8444' is not a recognized coordinator origin."
[FAIL] average-code-fetch-time
  promise_test: Unhandled rejection with value: object "DataError: Failed to execute 'runAdAuction' on 'Navigator': aggregationCoordinatorOrigin 'https://web-platform.test:8444' is not a recognized coordinator origin."
[FAIL] percent-scripts-timeout
  promise_test: Unhandled rejection with value: object "DataError: Failed to execute 'runAdAuction' on 'Navigator': aggregationCoordinatorOrigin 'https://web-platform.test:8444' is not a recognized coordinator origin."
[FAIL] participating-ig-count
  promise_test: Unhandled rejection with value: object "DataError: Failed to execute 'runAdAuction' on 'Navigator': aggregationCoordinatorOrigin 'https://web-platform.test:8444' is not a recognized coordinator origin."
[FAIL] percent-igs-cumulative-timeout, and cumulative-buyer-time when hit
  promise_test: Unhandled rejection with value: object "DataError: Failed to execute 'runAdAuction' on 'Navigator': aggregationCoordinatorOrigin 'https://web-platform.test:8444' is not a recognized coordinator origin."
Harness: the test ran to completion.

