Tests exception message from eval on nested worker context in console contains stack trace.

            function foo()
            {
                throw {a:239};
            }
            function boo()
            {
                foo();
            }
            boo();
VM:3 Uncaught {a: 239}a: 239[[Prototype]]: Object
foo @ VM:3
boo @ VM:7
(anonymous) @ VM:9

